BEGIN TRANSACTION;
CREATE TABLE `Palya` ( `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `Nev` TEXT NOT NULL );
INSERT INTO `Palya` VALUES (1,'Kezdet');
CREATE TABLE `Kinezet` (
	`ID`	INTEGER NOT NULL,
	`Nev`	TEXT NOT NULL,
	PRIMARY KEY(`ID`)
);
INSERT INTO `Kinezet` VALUES (1,'Alap');
CREATE TABLE `Jatekadat` (
	`FelhasznaloID`	INTEGER,
	`Penz`	INTEGER,
	`AktivSzint`	INTEGER,
	`AktivKinezetID`	INTEGER,
	FOREIGN KEY(`FelhasznaloID`) REFERENCES `Felhasznalo`(`ID`),
	FOREIGN KEY(`AktivKinezetID`) REFERENCES `Kinezet`(`ID`)
);
CREATE TABLE "FelhasznaloPalyaAdat" ( `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `FelhID` INTEGER NOT NULL, `PalyaID` INTEGER NOT NULL, `LegjobbIdo` INTEGER, FOREIGN KEY(`FelhID`) REFERENCES `Felhasznalo`(`ID`), FOREIGN KEY(`PalyaID`) REFERENCES `Palya`(`ID`) );
CREATE TABLE `Felhasznalo` (
	`ID`	INTEGER NOT NULL,
	`Kor`	INTEGER NOT NULL,
	`Nev`	TEXT NOT NULL,
	PRIMARY KEY(`ID`)
);
COMMIT;
